joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1     # Forward/Backward on Axis 1
    scale_linear:
      x: 2.0
    axis_angular:
      yaw: 0   # Left/Right on Axis 0
    scale_angular:
      yaw: 2.0

    enable_button: 6         # LB deadman
    require_enable_button: true
