teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.7

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 4.5

    enable_button: 6

    require_enable_button: true
